"""Added chains to bg-chain

Revision ID: 485446b03fa7
Revises: a8b6a2a68596
Create Date: 2025-01-12 03:21:18.627901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '485446b03fa7'
down_revision: Union[str, None] = 'a8b6a2a68596'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
