"""Initial tables: users, messages, abilities

Revision ID: 59ed5dae3a3b
Revises: 
Create Date: 2025-01-06 23:15:56.042125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '59ed5dae3a3b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_id', table_name='messages')
    op.drop_index('ix_messages_user_id', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_abilities_id', table_name='abilities')
    op.drop_index('ix_abilities_tool_name', table_name='abilities')
    op.drop_table('abilities')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(), nullable=False),
    sa.Column('last_name', sa.VARCHAR(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('is_admin', sa.BOOLEAN(), nullable=True),
    sa.Column('is_subscribed', sa.BOOLEAN(), nullable=False),
    sa.Column('refresh_token', sa.VARCHAR(), nullable=True),
    sa.Column('picture', sa.VARCHAR(), nullable=True),
    sa.Column('location', sqlite.JSON(), nullable=True),
    sa.Column('is_guest', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=1)
    op.create_table('abilities',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tool_name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('args', sqlite.JSON(), nullable=True),
    sa.Column('output', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_abilities_tool_name', 'abilities', ['tool_name'], unique=1)
    op.create_index('ix_abilities_id', 'abilities', ['id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('chain_id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('from_agent', sa.VARCHAR(), nullable=False),
    sa.Column('to_agent', sa.VARCHAR(), nullable=False),
    sa.Column('message', sa.VARCHAR(), nullable=False),
    sa.Column('args', sqlite.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_user_id', 'messages', ['user_id'], unique=False)
    op.create_index('ix_messages_id', 'messages', ['id'], unique=False)
    # ### end Alembic commands ###
