"""Initial schema

Revision ID: a8b6a2a68596
Revises: bccefd864935
Create Date: 2025-01-12 03:08:37.620062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8b6a2a68596'
down_revision: Union[str, None] = 'bccefd864935'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bg_chain_id', table_name='bg_chain')
    op.drop_table('bg_chain')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bg_chain',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chain_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='bg_chain_pkey')
    )
    op.create_index('ix_bg_chain_id', 'bg_chain', ['id'], unique=False)
    # ### end Alembic commands ###
